### ISSUE TITLE
Fix resolution

### ISSUE THREAD

**Issue by PaulFasola** [PaulFasola/android_device_huawei_next#12]
Actually an higher DPI is used to balance with the wrong resolution (not set in the build.prop).

For app compat (like Twitter) this have to be fixed.

**Comment by ghost** [comment]
Hi, I've been following your progress for a while now and I thought that I'd chime in. Perhaps something like this might fix your screen oddities:
https://github.com/Meticulus/android_device_huawei_hi6250/blob/master/BoardConfig.mk#L99

**Comment by PaulFasola** [comment]
Updated, thanks !  Indeed, this is an xxhdpi (and not hdpi) screen. DPI value also updated.
Screen is still glitchy however

**Comment by ghost** [comment]
If you are experiencing rippling and tearing you might try this:
https://github.com/Meticulus/android_device_huawei_hi6250/commit/02154023861dd677652799e5ab84a276c1a75aae

though most bump this down to 3...

**Comment by PaulFasola** [comment]
This fixed the issue, thanks again!
