### ISSUE TITLE
Fix HwComposer

### ISSUE THREAD

**Issue by PaulFasola** [PaulFasola/android_device_huawei_next#14]
Screen can't wake up from deep sleep mode

Original HAL lib is causing fatal exception on boot and we don't want to include the asked libs (EMUI related).

Trying a custom imp. right now

**Comment by ghost** [comment]
hi6250 had an issue with deep sleep in the beginning this is what fixed it: https://github.com/Meticulus/android_device_huawei_hi6250/commit/793cf2f630fcc86769b8692ade66e722b78cb324

I had commented those lines out myself and if I hadn't done that then we never would have had that problem. If you can not find similar lines somewhere in your init script it might be worth trying to put these in somewhere; given that the paths are valid... I've learned that huawei often uses vendor init do to these things...

Also, if you need anything...

**Comment by PaulFasola** [comment]
Those lines exists and are not commented but thanks anyway :)
I'm investigating on a possible issue in the ramdisk concerning power init

SoD sucks.

**Comment by XePeleato** [comment]
@PaulFasola Have you tried this patch?
https://github.com/XePeleato/hisi_frameworks_native/commit/2b5fe589a7cc2223a344e56d84e450041756656a

By the way: The original source of the HwC module you're using is here: https://github.com/XePeleato/Hisi_HwComposer

**Comment by PaulFasola** [comment]
Trying it right now, thanks !

Sorry mb for the HwC implementation, thought it was Surdu Pertru's stuff (based on his readme). I'll update that.

**Comment by PaulFasola** [comment]
The issue seems to be resolved, kudos ! And thank you.

**Comment by imchivaa** [comment]
Good job on solving this everyone ....
