### ISSUE TITLE
Constant lag / slowdown when transitioning 

### ISSUE THREAD

**Issue by Fatihnetic** [PaulFasola/android_device_huawei_next#16]
- When we play a music while doing something else (anything, browsing on google maps or pulling down    the notification bar) the audio will cut for a fraction of a second. The o/s will lag/hang 

- General slowdown at moments

Looks like to be something eating CPU ressources in the background.

**Comment by imchivaa** [comment]
I use Spotify, and no issues. But native music player isn't playing any music. Able to see but tapping the song isn't playing it.

**Comment by imchivaa** [comment]
UI lag sometimes, but not much, especially when closing all apps in the recent app. I guess enhancement can be done last? So far, good job.

**Comment by Fatihnetic** [comment]
@imchivaa thanks for the info on your side.

Probably something to do with my install ? I'm on NXT-L29 
Can you try this : Play a spotify music, go on the main screen (desktop or what ever) and pull down the notification bar a couple times while the music is playing in the background. Notice any cutoffs ?

If not, I will reinstall. I used the full Goggle apps package. Have you used the pico or something ?

**Comment by Fatihnetic** [comment]
Never mind! Formatted cache, data, user data and system via TWRP and re-flashed Cynanogenmod +Pico Gapps. Working perfectly now. Will close :)

**Comment by PaulFasola** [comment]
Always working this way :) Some interferences with the old in place system ;) Glad this works.
