### ISSUE TITLE
GPS works for some apps only

### ISSUE THREAD

**Issue by cih997** [PaulFasola/android_device_huawei_next#22]
Alpha 5, NXT-L29.

GPS enabled, status high accuracy.

Google Maps detects GPS correctly. Some other apps do not.

Also in Location settings Maps status is High battery usage and the other apps are Low battery usage.

Is it known issue?

**Comment by PaulFasola** [comment]
GPS is in fact not (yet) fully enabled/implemented :)
The battery drain is because of all the bunch of bad wakelocks coming from the concerned deamons/the use of GPS over data.

I'm on it at this time, thanks ;)

**Comment by cih997** [comment]
Okay cool.

Interesting part is Google Maps - it's working perfectly with detailed position tracking so somehow it can enable GPS but other apps cannot :)

**Comment by PaulFasola** [comment]
Yep, same issue here ;) GPS and Camera are the priorities for the upcoming release

**Comment by PaulFasola** [comment]
The GPS module is now online, but I can't acquire any signal for now

**Comment by PaulFasola** [comment]
Fixed, available in the next build! 
![img_-t7l7cj](https://cloud.githubusercontent.com/assets/1634645/24299170/919007ee-10a8-11e7-9807-52de106e28f6.jpg)

Reopen if you have any issue after that.
