### ISSUE TITLE
Fix RIL

### ISSUE THREAD

**Issue by PaulFasola** [PaulFasola/android_device_huawei_next#6]
- SIM 1 detected

**Comment by PaulFasola** [comment]
Fixed - Multi-SIM online

**Comment by Syl191** [comment]
Salut , je porte Ressurection Remix sur le Honor 8 , tout est stable , cependant le signal est mal affiché (1 barres au lieu de 4)
j'ai vu que tu as eu ce problème , comment l'as tu fixé ? Merci.

**Comment by PaulFasola** [comment]
Hello !
Il suffit de créer et d'injecter sa propre implémentation de RIL puis préciser son utilisation dans le BoardConfig (regarde _BOARD_RIL_CLASS_, les exemples ne manquent pas).

Enfin, dans le system.prop, il ne faut pas oublier de préciser que tu ne souhaites pas utiliser la class par défaut : 
`ro.telephony.ril_class=<taclass>`

**Le framework en question :**
frameworks/base/telephony/java/android/telephony

**Le repo (CM en exemple):** 
https://github.com/CyanogenMod/android_frameworks_base/tree/cm-14.1/telephony/java
