### ISSUE TITLE
Hanging display on boot

### ISSUE THREAD

**Issue by PaulFasola** [PaulFasola/android_device_huawei_next#8]
WindowManager: ***** BOOT TIMEOUT: forcing display enabled

- need opti

**Comment by PaulFasola** [comment]
Fixed.

**Comment by CarlosArriagaCM** [comment]
how to fix? i have same error

**Comment by PaulFasola** [comment]
This is a very old issue, I can't remember which was the fix (and it can be many things at this state).
Could you give more details ? (any repo? xiaomi_rolex ?)

**Comment by CarlosArriagaCM** [comment]
yeah this https://github.com/CarlosArriagaCM/android_device_xiaomi_rolex

log error
https://gist.github.com/CarlosArriagaCM/cab97904d76cc0e2c6326fe1c0fbfa9d
