### ISSUE TITLE
Fix Radio

### ISSUE THREAD

**Issue by PaulFasola** [PaulFasola/android_device_huawei_next#9]
11-30 13:35:06.232   372   372 E RadioService: couldn't load radio module radio.primary (No such file or directory)

**Comment by PaulFasola** [comment]
Fixed

**Comment by cih997** [comment]
Not sure if my issue is related to this but with latest OTA I've noticed that internet connection (LTE / 3G etc.) drops quite often, much more often comparing to Kang VIP rom I've been using previously.

For example when I am traveling LTE connection is there, suddenly internet is down (no LTE / 3G icon in network status) in area where coverage is very good and there were no issues before.

When I enable and disable aeroplane mode the internet connection is back and full speed. It looks like an issue with reconnecting when changing BTS or something like that.

Is that any known Huawei / Lineage OS / this build issue?

**Comment by cih997** [comment]
One more interesting info here - when LTE connection is down (even if full coverage and there should be LTE connection working), when I lock and unlock the phone connection is back for some random time. This is repeatable.

**Comment by cih997** [comment]
Another insteresting spot is that when network connection status is disconnected (no signal bars), I can see the network name like I would be connected. However I cannot make / receive calls nor send / receive texts.

**Comment by PaulFasola** [comment]
I encountered this issue with my L-29. The signal strength is managed by the java part with a specific class and this one is (seemingly) reporting the signal wrongly. I'm currently focusing on the AL-10/L-09 RIL issues for now because L-09 users don't even have their sim cards detected. This issue is in my TODO and I'll start to focus on it right after.

Kang VIP is a stable ROM seems mainly based on the stock one (but customised/tweaked as hell). This one is in Alpha stage so basically for testers and shouldn't be your main ROM (even if there is no critical issues anymore).

**Comment by cih997** [comment]
Thanks Paul. I found original and KangVIP ROMs extremely buggy and useless (missing notifications from various of app etc. and I tried many solutions to get these worked / fixed) and Lineage OS, even in Alpha version is way better in my opinion.
